syntax on
filetype off
set number
set list
set listchars=trail:•
set ignorecase
set smartcase
set incsearch
set hlsearch
set ttimeoutlen=10
set backspace=indent,eol,start
set expandtab tabstop=2 shiftwidth=2

"set runtime path to include Vundle
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-dispatch'
Plugin 'scrooloose/nerdtree'
Plugin 'kien/ctrlp.vim'
Plugin 'scrooloose/nerdcommenter'
Plugin 'epmatsw/ag.vim'
Plugin 'sjl/vitality.vim'
Plugin 'sjl/gundo.vim'
Plugin 'tpope/tpope-vim-abolish'
Plugin 'tpope/vim-projectionist'
Plugin 'kien/rainbow_parentheses.vim'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'w0rp/ale'
Plugin 'regreplop.vim'
Plugin 'ervandew/supertab'
Plugin 'tpope/vim-unimpaired'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-repeat'
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'tomtom/tlib_vim'
Plugin 'garbas/vim-snipmate'
Plugin 'honza/vim-snippets'
Plugin 'davidhalter/jedi-vim'
Plugin 'elixir-editors/vim-elixir'
Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'
Plugin 'alampros/vim-styled-jsx'
Plugin 'YankRing.vim'
Plugin 'ZoomWin'
call vundle#end()

filetype plugin indent on

runtime! init/**.vim
